### ISSUE TITLE
ActiveDirectoryでのドメイン参加Ansible版を作成

### ISSUE THREAD

**Issue by MITLabo** [shiftrepo/OperationBreakingDawn#47]
**Describe the solution you'd like**
Ansibleで構築する。

**Comment by MITLabo** [comment]
DNSエラーが出るが、問題はない。ADにも追加される。
```
[root@repository AD]# net join -U Administrator
Enter Administrator's password:
Using short domain name -- SHIFT
Joined 'REPOSITORY' to dns domain 'ad.shift.com'
No DNS domain configured for repository. Unable to perform DNS Update.
DNS update failed: NT_STATUS_INVALID_PARAMETER
```
hostsのFQDN設定とネットワークへのドメインサーチでOK。hostsの記載順序を間違えないこと。
```
192.168.10.57 repository.ad.shift.com repository 
```

**Comment by y-mineshima** [comment]
念のため
この処理ですが、正しく処理するためにはnet コマンドの前に、hostsの設定を行ったほうがbetterです。確か、ドメインを抜ける際に、AD側に情報が残るという問題があった気がします。

また、本コマンドによりドメイン参加を行うと、強制的にホスト名が大文字に変化するバグもあります。
このため、小文字のホスト名を維持したい場合は、netコマンドでドメイン参加後に、レジストリを2か所変更する必要があります。レジストリの具体的なパスは、会社にいって確認しますね。
（元PCチームより）
